Intel-Media-SDK/infrastructure

- build_scripts/build_runner.py
"last_build" file creates for each product type
> [Build scripts] Added "embedded_private" product type;

- bb/master/config.py
- bb/master/master.cfg
- bb/master/msdk_secrets.py.example
- common/mediasdk_directories.py
- Add embedded support
- Minor fixes
> Embedded support

- bb/master/config.py
- bb/master/master.cfg
- bb/master/msdk_secrets.py.example
- Changed name of Buildbot page (for private mode) `MediaSDK Private`
- Add variable `MASTER_PRODUCT_TYPE`
- Disabled `waterfall_view` and `grid_view`
- Add worker names for private buildbot
> [buildbot] Fixes for embedded

- build_scripts/build_runner.py
traceback from Python subprocess does not show;
only errors show in output; full logs available in logs file on share
> [CI logs] Updated Buildbot output

- README.md
In addition add some information about polling
> [docs] Add section about builds reproducing

- build_scripts/build_runner.py
Changed mask for linux builds errors
> [CI build scripts] Errors output fix

- bb/master/master.cfg
in accordance with https://github.com/Intel-Media-SDK/product-configs/pull/6
> [Buildbot][don't merge] Change build config filenames

- build_scripts/build_runner.py
Added variable for layout for Install pkg
> [CI build scripts][do not merge] Conf for Install package

- build_scripts/build_runner.py
Added multiple masks for searching errors in output
> [CI build scripts] Build logs parser update

- build_scripts/build_runner.py
- common/helper.py
Reverts Intel-Media-SDK/infrastructure#59
> Revert "Strip binaries"

- build_scripts/build_runner.py
Flag added for action() and vs_component().
If verbose == True, all logs will be shown in output.
Also "log" object can be used in
custom functions in product configurations.
> [CI build scripts] Added "verbose" flag

- README.md
- build_scripts/build_runner.py
Throwing arguments from command line interface of build scripts to
build configuration available now
> [CI build scripts] Transferring arguments from command line

- build_scripts/build_runner.py
- common/helper.py
Added 'verbose' argument for cmd_exec;
'_strip_bins' function writes logs only to a log file
> [CI build scripts] Binaries stripping

- build_scripts/build_runner.py
Need for matching actions in product configuration without adding cli argument
> [Build scripts] Add "product_type" parameter in build configs

- ted_adapter/test_adapter.py
Enabled working with .gz archives
> [TED adapter] Hot fix

- build_scripts/build_runner.py
build_event throws to product config file;
created three product types for windows;
> [Closed CI] Build runner updates

- ted_adapter/test_adapter.py
> [test_adapter] Disable sudo operations at all

- common/mediasdk_directories.py
We can't show closed source repositories on github
> [Build script] Removed mdp_msdk-omx-plugins and mdp_msdk-c2-plugins

- bb/master/config.py
- build_scripts/build_runner.py
- common/helper.py
- ted_adapter/test_adapter.py
Move product type, build type, build event choices to constants
> Refactoring for scripts 

- smoke_test/config.py
- smoke_test/hevc_fei_smoke_test.py
Moved get_sample_folder function execution from constants
> Getting samples folder dynamically

- build_scripts/build_runner.py
- common/build_number.py
Created module build_number.py
Getting API version for Windows builds moved to build scripts
get_build_number(), get_api_version() and branch_name are trow to
product configs
> [Build scripts] Updates for weekly

- smoke_test/config.py
- smoke_test/hevc_fei_smoke_test.py
> [Tests] Refactoring for hevc_fei

- common/git_worker.py
- this commit removes the error of the 'commit_id' field in the exported
'repo_states.json' file
> To fix the 'repo_states.json' file generating

- bb/master/master.cfg
- common/build_number.py
- fixed import for buildbot master
> Fix for increasing build number

- bb/master/master.cfg
- build_scripts/build_runner.py
- common/extract_repo.py
- common/git_worker.py
- common/mediasdk_directories.py
-Release branches are defined and all repos are switched to the release branch
git_worker.revert_commit_by_time() does not work with old version of git. Need to investigate.
> Implemented switching to release branches

- common/mediasdk_directories.py
- ted_adapter/test_adapter.py
Dependency specification for installing rpm/deb packages in test scripts
> [Test scripts] Added dependency specification

- common/git_worker.py
Add fetch all to get remote branches
> Fix switch to release branch

- bb/master/config.py
- bb/master/master.cfg
This builder is a root builder for all builds/tests/etc which can be started for change in VCS
PS: this builder will sent own status to review immediately (10~20 sec after creating commit) - it gives possibility to easily debug the service without parsing logs
PPS: deleted NextGEN flow
> [Buildbot] Added "trigger" builder

- common/mediasdk_directories.py
- common/package_manager.py
- ted_adapter/test_adapter.py
Add installing mediasdk package before every testing
> [test scripts] implemented installing msdk via rpm/deb package

- bb/master/master.cfg
- common/mediasdk_directories.py
- unused imports has been removed
> Updated pull request filter

- build_scripts/build_runner.py
- common/helper.py
added packing functionality to common.helper
> moved pack to common

- bb/master/GitHubPullrequestPoller.patch
- bb/master/buildbot.tac
- Added .tac file for buildbot master
> Added patch for pull request poller

- common/package_manager.py
- ted_adapter/test_adapter.py
Made package finding case insensitive
Added logging
> [Test scripts] Fixed package finding/removing

- build_scripts/build_runner.py
- common/git_worker.py
Fix for correct slicing repo states
> [Git worker] Check triggered repo for extract stage

- common/git_worker.py
"git fetch" for Gerrit patches instead of "git pull"
> [Git worker] Fix checkout to branches for Gerrit

- common/static_public_data.py
Added media-driver repo to REPOSITORIES set for config
> Added media-driver repo

- common/static_public_data.py
Added path to open source gmmlib git repo
> Added GmmLib repo

- common/mediasdk_directories.py
Added pattern to define release branch mss2018_r2
> Added pattern for release branch mss2018_r2

- common/git_worker.py
Extraction stage fails without retries
if revision or branch does not exist
> [Git worker] Append some logic for checkout retries

- common/git_worker.py
returned list includes commit_from
> [Git worker] get_commits function update

- common/mediasdk_directories.py
Minor fixes for github branches
> [Common] mediasdk_directories.py updates

- bb/master/master.cfg
- revert https://github.com/Intel-Media-SDK/infrastructure/pull/189
> Removed commit-time argument from build script cmd

- bb/driver/config.py
- bb/driver/master.py
- Builds for commits in product configs repository will be started
only if files in driver folder were modified
> [Buildbot][Driver] Changed rule of starting builds for configs repo

- common/static_public_data.py
Need to clone the repos to build igc
> Added dependency repos for intel-graphics-compiler

- build_scripts/build_runner.py
- common/helper.py
- common/manifest_manager.py
- requirements.txt
+ Manifest has empty constructor;
+ add PUBLIC_LINUX_GMMLIB product type;
> [Manifest] Save manifest file after extract stage

- bb/utils.py
> [Buildbot] Fixed pull request filter

- build_scripts/build_runner.py
Added copy func to build scripts to make repo structure for intel-graphics-compiler build
> Add copy to api 

- common/static_public_data.py
> Add graphics compute runtime repo

- build_scripts/build_runner.py
It is needed in order to update configs with different suffixes
> Add suffix to update_config method

- bb/driver/master.py
- bb/master/config.py
- bb/master/factories.py
- bb/master/master.py
- bb/utils.py
- requirements.txt
- Added support of windows paths for open source buildbot
- Added running pylint as pre-commit check for each modified .py file
> [Buildbot] Added pre-commit checks for Infrastructure repo

- build_scripts/build_runner.py
- build_scripts/common_runner.py
- common/helper.py
It is needed for configuration, where we should create and pack addition file with environment settings.
> Add method for creating file

- bb/driver/master.py
- bb/factories.py
- fixed path to test directory for driver tests
> [Buildbot][Driver] Enable notifications from all builders

- bb/factories.py
- bb/master/config.py
- [Mediasdk] Added igc and opencl dependencies for test builder
This dependencies will be build for master and 19.1 branches
> [Buildbot] Use pre_commit build event

- common/helper.py
Return code to use in clean script
> Add return code for success

- bb/factories.py
- bb/utils.py
Fixed 2 problem:
- Fixed filtration by change information.
- Trigger will create request if it is last by time.
> [Buildbot] Fix for scheduling

- common/component_checker.py
- Only if artifacts does exists on share
> Added link on artifacts in component checker output

- build_scripts/manifest_runner.py
- common/branch_converter.py
- common/extract_repo.py
- common/manifest_manager.py
- common/mediasdk_directories.py
> [One CI][Manifest runner] Completed prototype of manifest runner

- build_scripts/build_runner.py
- build_scripts/common_runner.py
- common/git_worker.py
- common/static_public_data.py
repo_states and changed_repo are not used any more
> [One CI][Build runner] Use new API of manifest manager

- build_scripts/build_runner.py
- build_scripts/manifest_runner.py
- build_scripts/tests_runner.py
- common/component_checker.py
- common/manifest_manager.py
- test_scripts/components_installer.py
Functions for getting artifacts layout by manifest
> [One CI][Manifest manager][Proto] Layout functions

- bb/factories.py
- bb/master/config.py
- build_scripts/build_runner.py
- common/static_public_data.py
> Enable windows build in open source CI service

- bb/factories.py
- bb/master/config.py
- bb/master/master.py
- bb/utils.py
> [One CI] Added Libva utils builder

- build_scripts/build_runner.py
- build_scripts/common_runner.py
- build_scripts/tests_runner.py
- common/extract_repo.py
- common/git_worker.py
- common/helper.py
- common/mediasdk_directories.py
Added the proxy parameter to the with_proxies() decorator
Added the with_proxies() decorator to the Action.run()
Added the test stage to the build_runner.py
Added check for return value of callfunc in the Action.run()
Added the extract_repo() function
Fixed the test runner to use absolute work dir path
Several fixes and improvements
> Several fixes and improvements

- bb/factories.py
- bb/master/config.py
> [Buildbot] ONE CI Cleanup

- bb/master/config.py
- common/helper.py
- Temporary disabled auto-update gmmlib\libva versions
> [Buildbot] Switch to gcc 9.2

- build_scripts/tests_runner.py
- common/package_manager.py
+ override method for executing all tests in case of fails (tests_runner)
> [CI][Package manager] Use rpm and dpkg for working with packages

- build_scripts/build_runner.py
Reverts Intel-Media-SDK/infrastructure#341
> Revert "[CI][Build] Move stripping binaries to Pack stage"

- bb/factories.py
- bb/master/config.py
- bb/utils.py
- Allow describe different behavior for pre-commits and commits
> [Buildbot] Improve triggering logic for builders

- build_scripts/common_runner.py
- common/helper.py
+ update for modifying PATH environment variable
> [CI][Infra] Add build event

- bb/buildbot_utils.py
- Added unicode icons for statuses
> [Buildbot] Extend BuildStatus class

- common/helper.py
> Added closed_windows_va to product_type

- bb/master/config.py
- Fixed names of linux Docker build workers
> [Buildbot] Removed linux VM build workers

- bb/master/config.py
> Revert "[Buildbot] Temporary disable igc build"
