bb/master/config.py
bb/master/master.cfg
bb/master/msdk_secrets.py.example

- Implemented Pollers:
- `GitPoller`
- `GithubPullRequestPoller` - implemented but **disabled** because need support on the side of `build_scripts`
- GitHub webhook receiver removed (full alternative is `GitPoller`)
- Some minor changes in config.py to improve readability
Pollers are tested for the stable work **in** and **out** of the Intel`s infrastructure.
P.S.  
To enable GitHub webhook need to:
- Add `c["www"]["change_hook_dialects"] = ...`
- Add `project=config.GITHUB_REPOSITORY` instead of `category` in `ChangeFilter`
- Add `GITHUB_WEBHOOK_SECRET = "my_password"` in `msdk_secrets.py.example`

[buildbot] Implement Pollers

---

build_scripts/build_runner.py

I've added unnecessary argument '--fork-url' for CI builds from forked repository. 
Argument '--changed-repo' stays without changes, so if we want to run build for 'MediaSDK' from fork, we must send these arguments with next values (for example):
--changed-repo="MediaSDK:master:8cb6c52f18dbeedc54eb192faaa00c17b99aceec" --fork-url="https://github.com/dlobanox/MediaSDK.git"

[CI build scripts] Building from forked repo

---

bb/master/config.py
bb/master/master.cfg
build_scripts/build_runner.py
common/mediasdk_directories.py

This features is needed mainly for external contributors.  
- `--fork-url` starts in all cases (Pull Requests from forked and not forked repositories) (but it isn\`t mandatory by it\`s nature)
- Add new folder `repos_forked` which is cleaned before each extracting (to prevent conflicts because of same names of repositories)
- Decision about current type of repository (fork or official), from which we have to `pull` the changes, is on the side of `build_runner.py`

Add CI for Pull Requests from forked repositories

---

build_scripts/build_runner.py
common/git_worker.py

Build scripts can run with sources file.
In this case next arguments do not need to use:
--changed-repo,
--build-type,
--product-type,
--build-event,
--commit-time.
Also stages "install", "pack", "copy"
are not available with "--sources" argument
If --changed-repo and --sources are set, --sources will be ignored.
+ some updates in git_worker:
improving sources.json file
HEAD instead of SHA sum available in --changed-repo

[CI build scripts] Running script with 'repo_states.json' file

---

build_scripts/build_runner.py

clean.log file does not create while cleaning
because it affects retrying of clean stage.
Clean logs writes only to default
file "_all.log" in build_scripts directory.

[CI build scripts] clean.log disabling

---

build_scripts/build_runner.py

Error occurs if repo_states.json has more repositories than build config.
Fixed by adding IF statement

[CI build scripts] repo states fix

---

bb/master/config.py
bb/master/master.cfg
build_scripts/build_runner.py

- Add clang CI
- Refactoring: add dynamic creation of schedulers, builders and factories
- More comments and explaining
- Improved `config.py` logic
- Add new aux worker "b-1-18aux"
As a result after the refactoring we can add new `BUILDERS` very easy.
Some basic logic:
- use of strict association of scheduler - builder
- new worker pool tagging (which can be discussed)
Needed change: https://github.com/Intel-Media-SDK/product-configs/pull/22

Add clang and dynamic creation in Builbot

---

bb/master/config.py

Disable builder because machine is not ready yet.

[buildbot] Temporary disable builder `build-api-next-no-x11`

---

build_scripts/build_runner.py
common/git_worker.py

- the error checking of "--changed-repo" and "--repo-states" parameters is removed
- new warning messages are added
- new comments are added
- the 'copy' stage is updated

[Build scripts] To build HEAD revision

---

bb/master/config.py
bb/master/master.cfg
build_scripts/build_runner.py
common/mediasdk_directories.py

- Changed pollers strategy - GitPoller works only for release branches,
GitHubPullRequestPoller works for all pull requests
- Added "target_branch" properties to correct extracting infrastructure\product
repositories
- Added dynamic factories

Added deploying infrastructure from release branches

---

common/git_worker.py

Moved fetch all branches to prepare_repo function that is called before checkout. 
This is needed to checkout by commit_id in third parties such as LibVA.

Added fetch to prepare_repo

---

bb/master/config.py

- mss2018_r2 branch not supported building fastboot configuration

Disable fastboot build for mss2018_r2 branch

---

bb/driver/master.py

- Disable notifications from 'trigger' builder.

[Buildbot][Driver] Notifications will send 'build' builder only

---

bb/driver/config.py
bb/driver/master.py
build_scripts/tests_runner.py

- Changed worker name and names of test stages.
- Specified correct product type and component name.
- Added notifications for tests.
- Added return from copy stage in test scripts, because this stage failed without it.

Fixes for driver tests

---

build_scripts/build_runner.py

The 'BuildGenerator.changed_repo_name' class field will be setup 'None' if the 'changed_repo' CLI parameter is not set. This helps to avoid the 'BuildGenerator._global_vars.update' method fall.

Fix build_runner for HEAD revision build

---

pre_commit_checks/check_copyright/check_copyright.py

The comment string detection fixed, the error was in the searching of
the position of the comment end.

To fix copyright check

---

bb/driver/master.py
bb/master/master.py
bb/utils.py

- This branch created for development One CI.
Production CI can not work correctly for this branch because
all script will be redesigned in it.

[Buildbot] Temporary disable event for one_ci_dev branch

---

common/git_worker.py

Git blame throws exception if file was generated while building
(it does not exist in commit)

[Git worker] Update method

---

build_scripts/build_runner.py
build_scripts/manifest_runner.py
common/manifest_manager.py

PRODUCT_REPOS list in build configurations can be used for filtering
repositories that will be extracted.

[One CI][Runners] New behavior for build and manifest runners

---

bb/master/config.py

This change is needed to create separated builder column
(to the right of trigger) which don't violates build\test grouping in UI,
because buildbot automatically group builders by name
Just for increasing usability of Console View

[Buildbot] Rename manifest updater

---

bb/factories.py
bb/master/config.py

- Factory\Builder are not needed because updater step is added to trigger factory

[Buildbot] Remove code duplication for manifest updater

---

bb/master/config.py

- Buildbot sent too many request to Github.
We can not decrease number of requests, but we can decrease number of
polling in a hour.

[Buildbot] Increased polling period from 60 to 120 seconds

---

bb/master/config.py

This is workaround to mitigate the problem with build chains scheduling, when some build
may not be triggered if they have 2 or more dependent builds which finished together.

[Buildbot] Workaround for scheduling driver builds

---

bb/master/config.py

- This need to unblock development until igc will be svitched to llvm10

[Buildbot] Temporary disable igc build

---

bb/factories.py

- We need extract mediasdk repository because ted tests
stored there since #2298 (last patch)

[Buildbot] Set mediasdk component for all tests
